name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: deps
        run: sudo apt install -y libglib2.0-dev libcurl4-gnutls-dev libcjson-dev check
      - name: dist
        run: ./autogen.sh; ./configure; make dist
      - name: Create Release
        id: create_release
        uses: "marvinpinto/action-automatic-releases@latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          draft: false
          prerelease: false
          files: |
            LICENSE
            *.tar.xz
            *.tar.gz
            *.tar.bz2