name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build: Create Release
  runs-on: ubuntu-latest
  steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Dist
      run: ./autogen.sh; ./configure; make dist
    - name: Create Release
      id: create_release
      uses: actions/create-release@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        files: |
          LICENSE
          *.tar.xz
          *.tar.gz
          *.tar.bz2